[package]
name = "bogominer"
description = "official open-source native bogosort miner for swapjs' bogostream."
authors = ["tomcat <hi@tomcat.sh>"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bogominer"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "native-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "5"
num_cpus = "1"
parking_lot = "0.12"
tauri = { version = "2", features = ["devtools"] }
urlencoding = "2"
tauri-plugin-opener = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[build-dependencies]
tauri-build = { version = "2", features = [] }
